name: dart_airtable
description: Dart library for working and interacting with the Airtable API 
version: 0.1.2
homepage: https://www.github.com/deriegle/dart-airtable

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.13.3
  meta: ^1.1.8

dev_dependencies:
  dotenv: ^3.0.0
  pedantic: ^1.8.0
  test: ^1.6.0
